repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.15.0
    hooks:
      - id: eslint
        name: ESLint
        files: "terraform/.*\\.ts$|application/.*\\.ts$"

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        name: Hadolint
        files: "Dockerfile"

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.312
    hooks:
      - id: checkov
        name: Checkov
        files: "terraform/.*\\.ts$"
