apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sisu-tech-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedbadawy4/app-work.git
    targetRevision: HEAD
    path: k8s/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
