name: Publish Docker Image to GCR

on:
  push:
    branches:
      - main
      - dev
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest # Prefer self-hosted runners for secure builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate with GCP
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > gcloud-key.json
          gcloud auth activate-service-account --key-file=gcloud-key.json
          gcloud auth configure-docker gcr.io --quiet

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sisu-tech:latest .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sisu-tech:latest
